spring.application.name=revenda

#conexao com o banco 7
spring.datasource.url=jdbc:postgresql://localhost:5433/revenda
spring.datasource.username=revenda_user
spring.datasource.password=revenda_pass
spring.datasource.driver-class-name=org.postgresql.Driver

#jpa/ hibernate 1
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# flyway 6
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration