CREATE TABLE cliente (
    id BIGSERIAL PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    cpf VARCHAR (14) NOT NULL UNIQUE,
    telefone VARCHAR (15) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    cidade VARCHAR(100) NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT now()
);